### ISSUE TITLE
how to make tool tip open when user hovers on the tooltip 

### ISSUE THREAD

**Issue by sagarCS** [3tmaan/react-hooks-tooltip#3]
hey, is it possible to make the tool tip open when the user hover over the tool tip body?

**Comment by 3tmaan** [comment]
hey, the hover is not supported for this repo, but you can add the related logic to your component to make it work:

`<div className={Styles.container} onMouseEnter={() => setState(true)}
       onMouseLeave={() => setState(!isVisible)}>...</div>`

I didn't give it a try, but it can be something around that. Hope it helps :)
